Integrity check for DIFF mode
Resolves #1226

diff --git a/.github/workflows/integrity.yml b/.github/workflows/integrity.yml
--- a/.github/workflows/integrity.yml
+++ b/.github/workflows/integrity.yml
@@ -36,3 +36,27 @@ jobs:
         run: |
           export TEST_MODE=yes
           make generate-devdoc
+
+      - name: Run quickstart and update in DIFF mode
+        env:
+          area: europe/monaco
+          QUIET: 1
+        run: |
+          echo MIN_ZOOM=0 >> .env
+          echo MAX_ZOOM=14 >> .env
+          echo DIFF_MODE=true >> .env
+          # Cleanup
+          rm -fr data build cache
+          # Create data/$area.repl.json
+          make download-geofabrik area=$area
+          # Download 2+ month old data
+          docker-compose run --rm --user=$(id -u):$(id -g) openmaptiles-tools sh -c "wget -O data/$area.osm.pbf http://download.geofabrik.de/$area-$(date --date="$(date +%Y-%m-15) -2 month" +'%y%m01').osm.pbf"
+          # Initial import and tile generation
+          ./quickstart.sh $area
+          # Download updates
+          # Loop to recover from potential "ERROR 429: Too Many Requests"
+          docker-compose run --rm --user=$(id -u):$(id -g) openmaptiles-tools sh -c "while ! osmupdate --keep-tempfiles --base-url=$(sed -n 's/ *\"replication_url\": //p' data/$area.repl.json) data/$area.osm.pbf data/changes.osc.gz ; do echo Sleeping...; sleep 630 ; done; echo Done."
+          # Import updates
+          make import-diff
+          # Generage new tiles
+          make generate-tiles-pg
